Роутинг на Express.js
paninebaluy/praktikum12 pull request #1
Opened 2020-03-20 13:52 UTC by paninebaluy

Реализован роутинг на локальном сервере (подробнее в Readme: https://github.com/paninebaluy/praktikum12)

*    По адресу http://localhost:3000/ доступен корень сайта.
*    По адресу http://localhost:3000/users возвращается JSON с пользователями.
*    По адресу http://localhost:3000/cards возвращается JSON с карточками.
*    По адресу http://localhost:3000/users/id (использовать id пользователя из JSON http://localhost:3000/users) возвращается JSON с данными конкретного пользователя
*    По несуществующем адресу возвращается статус-код 404 и сообщение об ошибке, по адресу с несуществующим id пользователя возвращается другое сообщение об ошибке и статус-код 404.

2020-03-21 05:01 UTC, mrprovoker commented
Добрый день!

Работа в целом хорошая. Отлично, что нет ошибок линтера. Очень хорошее README.
Но есть несколько критичных замечаний.


**Надо исправить:**
- Некорректно обрабатывается POST-запрос `http://localhost:3000/users/123`. Сейчас ответ приходит в виде HTML, а ожидается ответ в виде JSON: `{ message: 'Запрашиваемый ресурс не найден' }`. Аналогично и DELETE, PATCH и другие не GET-запросы. 
- По заданию в папке public должен находиться только собранный фронтенд приложения, а не исходники.
- Сейчас есть архитектурная проблема в приложении в папке routes:

1. Файл logging.js это router, это так называемая middleware. Рекомендуется все мидлвары держать в отдельной папке, например `middlewares`.
2. В файле router.js ожидается следующая схема.
Сейчас есть два пути /users и /cards. Соответственно было бы логичнее сгруппировать пути относящиеся к пользователям и карточка по разным файлам.

Поэтому в router.js можно сделать только:

```
const router = express.Router();

router
  	.use('/cards', cards)
  	.use('/users', users)
	.use('*', invalidUrl);

 module.exports = router;
```

В самих cards.js и users.js объявить роуты вместе с обработчиками. И соответственно экспортировать эти файлы будут роутеры, а не функции обработки.
3. Очень странное название у файла general.js. Это можно называть например `invalidRouter.js`


Можно лучше:
- В package.json в секции main указан файл `index.js`, такого файла в корне проекта нет.
- В package.json сейчас не заполнен description.
- В package.json в зависимостях указана бибилиотека `node-fetch`. Но судя по проекту она нигде не используется.
- Не понятно, почему отключено правило `// eslint-disable-next-line arrow-body-style`. Оно говорит о том, что запись можно сделать короче, без return.

При правках данный pull request закрывать/мерджить не надо. Все правки необходимо просто сделать новыми коммитами в этом же pull request'е.

Работу смогу принять только после устранения всех замечаний из пункта **Надо исправить**.

2020-03-22 04:34 UTC, mrprovoker requested changes
Спасибо за правки.

Появилось еще несколько проблем.

**Надо исправить:**
- Возможно я не совсем понятно выразился в предыдущем ревью. Сейчас есть единственная middleware - это logging.js. Ее отличие это наличие и использование next(). 
cards.js, invalidRoutes.js и users.js - это роутеры (они инициализируют и возращают express router) и должны находиться в директории `routes`. 
- В `getUserData.get('/:id',` есть проблема. Если пользователь будет не найден, то сначала вызовется `res.status(404).send(userNotFound);`, а потом сверху `  res.status(200).send(user);`. Необходимо добавить return у `res.status(404).send(userNotFound);` (в будущем это может приводить к серьезным ошибкам)


Можно лучше:
- Файл `routes/router.js` можно назвать `routes/index.js`. Тогда подключать его в app.js можно будет просто: `const router = require('./routes');`
- Хорошим стилем является в JS-файлах отделять пустой строкой подключение бибилиотек из `node_modules` и файлов из проекта. Например в файле `app.js`

Вопрос:
- Не понятно для чего в проекте файлы `backup_key` и `backup_key.pub`. Если данные файлы не относятся к проект - их не должно быть в репозитории.


При правках данный pull request закрывать/мерджить не надо. Все правки необходимо просто сделать новыми коммитами в этом же pull request'е.

Работу смогу принять только после устранения всех замечаний из пункта **Надо исправить**.

2020-03-22 06:44 UTC, paninebaluy commented
Оба файла из вопроса попали в репозиторий случайно :)
Спасибо!

2020-03-22 07:48 UTC, mrprovoker requested changes
Спасибо за правки. Проблем с предыдущего ревью нет.

Но остались проблемы с первого ревью:

**Надо исправить**:
- Некорректно обрабатывается POST-запрос `http://localhost:3000/users/123`. Подробнее описал возле проблемной строки.

Можно лучше:
- В package.json в секции main указан файл `index.js`, такого файла в корне проекта нет. Сейчас главный файл - это `app.js`

В остальном проект теперь выполнен отлично. Буду рад принять работу после исправления.

2020-03-22 07:48 UTC, mrprovoker commented on routes/invalidRoutes.js
> +invalidUrl.get('*', (req, res) => {
**Надо исправить:**
Некорректно обрабатывается POST-запрос http://localhost:3000/users/123. Сейчас ответ приходит в виде HTML, а ожидается ответ в виде JSON: { message: 'Запрашиваемый ресурс не найден' }. Аналогично и DELETE, PATCH и другие не GET-запросы

Подробнее можно почитать в официальной [документации](https://expressjs.com/ru/guide/routing.html) express. Особое внимание следует обратить на метод `app.all()`

2020-03-23 17:58 UTC, paninebaluy commented
Спасибо! Дошло, зачем нужно так обрабатывать все не-GET и неиспользуемые пока запросы (чтобы не было разброса  форматах ответа).

2020-03-24 15:16 UTC, mrprovoker approved these changes
Спасибо, теперь все отлично! 

Все пункты задания выполнены в полном объеме. Задание принято 👍

Желаю успехов в дальнейшем обучении!

2020-03-24 15:27 UTC, merged